[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["FUJIANKA Fumiya <uzuna.kf@gmail.com>"]
repository = "https://github.com/uzuna/rs-common"
rust-version = "1.76"

[workspace.dependencies]
anyhow = "1.0.95"
axum = "0.7.9"
byteorder = "1.5"
cfg-if = "1.0.0"
criterion = "0.5.1"
image = { version = "0.25", default-features = false }
jetson-pixfmt = { path = "crates/jetson-pixfmt" }
khronos-egl = "6.0.0"
mls-mpm = { path = "crates/mls-mpm" }
rand = "0.8.5"
rawproc = { path = "crates/rawproc" }
serde = "1.0.217"
thiserror = "2.0.11"
tokio = "1.43.0"
tokio-util = "0.7.13"
tower-http = "0.5.2"
tracing = "0.1"
tracing-subscriber = "0.3.19"
v4l = { git = "ssh://git@github.com/uzuna/libv4l-rs.git", rev = "740e727" }
v4l-serve = { path = "crates/v4l-serve" }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-util = { path = "crates/wasm-util" }
web-sys = "0.3"
xegl = { path = "crates/xegl" }

[profile.release.package.wasm-preview]
opt-level = "s"
