[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["FUJIANKA Fumiya <uzuna.kf@gmail.com>"]
repository = "https://github.com/uzuna/rs-common"
rust-version = "1.76"

[workspace.dependencies]
axum = "0.7.5"
byteorder = "1.5"
cfg-if = "1.0.0"
criterion = "0.5.1"
rand = "0.8.5"
tokio = "1.41.1"
tower-http = "0.5.0"
tracing = "0.1"
tracing-subscriber = "0.3.18"
v4l = { git = "ssh://git@github.com/uzuna/libv4l-rs.git", rev = "791ec17" }
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
wasm-util = { path = "crates/wasm-util" }
web-sys = "0.3"


[profile.release.package.wasm-preview]
opt-level = "s"
