[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["FUJIANKA Fumiya <uzuna.kf@gmail.com>"]
repository = "https://github.com/uzuna/rs-common"
rust-version = "1.71"

[workspace.dependencies]
byteorder = "1.5"
cfg-if = "1.0.0"
criterion = "0.5.1"
rand = "0.8.5"
