[workspace]
members = [
    "crates/*",
    "jetson/*",
    "examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["FUJIANKA Fumiya <uzuna.kf@gmail.com>"]
repository = "https://github.com/uzuna/rs-common"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
bytemuck = "1.23.0"
byteorder = "1.5"
cfg-if = "1.0.0"
clap = "4.5.38"
criterion = "0.5.1"
eframe = "0.31.1"
egui = "0.31.1"
fs-err = "3.1.0"
fxhash = "0.2.1"
image = { version = "0.25", default-features = false }
jetson-pixfmt = { path = "jetson/pixfmt" }
khronos-egl = "6.0.0"
mls-mpm = { path = "crates/mls-mpm" }
nalgebra = "0.33.2"
num-traits = "0.2.19"
rand = "0.9.1"
rawproc = { path = "crates/rawproc" }
serde = "1.0.219"
serde_yaml = "0.9.34"
tempfile = "3.20.0"
thiserror = "2.0.12"
tokio = "1.45.0"
tokio-util = "0.7.15"
tower-http = "0.6.4"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
v4l = { git = "ssh://git@github.com/uzuna/libv4l-rs.git", rev = "740e727" }
v4l-serve = { path = "crates/v4l-serve" }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-util = { path = "crates/wasm-util" }
wasmtime = "33.0.0"
wasmtime-wasi = "33.0.0"
web-sys = "0.3"
wgpu = "24.0.3"
wgpu-shader = { path = "crates/wgpu-shader" }
xegl = { path = "crates/xegl" }


[profile.release.package.wasm-preview]
opt-level = 3
