[package]
name = "mls-mpm"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nalgebra = "0.33.2"
num-traits = "0.2.19"
