[package]
name = "egui-learn"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
eframe = { workspace = true, features = ["wgpu"] }
egui.workspace = true
wgpu.workspace = true
