dir: plugins
pairs:
  - plugin: [hello, hasdep]
    file: hello.wasm
  - plugin: [hello, hasdep]
    wasi: preview2
    file: hello-wasip2.wasm
  - plugin: [hasdep]
    file: composed.wasm
  - plugin: [hasdep]
    file: hasdep.wasm
